name: fruitwash
description: Application Flutter FruitWash (IoT) – structure initiale
publish_to: "none"

version: 0.1.0+1

environment:
  sdk: ">=3.3.0 <4.0.0"
  flutter: ">=3.19.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  http: ^1.2.1
  shared_preferences: ^2.2.3
  intl: ^0.19.0
  mqtt_client: ^10.2.1
  flutter_riverpod: ^2.5.1
  google_fonts: ^6.2.1
  firebase_core: ^3.4.0
  firebase_database: ^11.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/translations/


